### ISSUE TITLE
Installing the MethylScore Docker without root privileges 

### ISSUE THREAD

**Issue by olaraym** [Computomics/MethylScore#8]
I tried pulling the Docker image with the code below:
podman pull quay.io/beckerlab/methylscore:nextflow

I got this error:
Error: writing blob: adding layer with blob "sha256:03d03471f75a7bdb7a20b9e79f743f235315f57f2d10e4b81e3c589f1224c95f": Error processing tar file(exit status 1): potentially insufficient UIDs or GIDs available in user namespace (requested 0:42 for /etc/gshadow): Check /etc/subuid and /etc/subgid: lchown /etc/gshadow: invalid argument

This error message indicates that I need to adjust my uids and gids, which is not possible at the moment because of rights.
@phue Please, what alternative approach is possible to get this package installed?

Thanks in anticipation of your assistance.

**Comment by phue** [comment]
I would suggest to either ask somebody with the required permissions to configure podman to work in [rootless-mode](https://github.com/containers/podman/blob/main/docs/tutorials/rootless_tutorial.md#etcsubuid-and-etcsubgid-configuration), or try [singularity](https://sylabs.io/singularity/)

**Comment by olaraym** [comment]
I got singularity to be installed; however, I am getting this error when I try to pull it:

Code ran : singularity pull quay.io/beckerlab/methylscore

FATAL: While pulling library images,  could not get image info: request did not succeed: UNAUTHORIZED: project quay.io not found: project quay.io not found (401 Unauthorized)

What could be the way out @phue

**Comment by phue** [comment]
Nextflow will take care of pulling the container when you start the pipeline with the `singularity` profile.

No need to do it manually, but if desired you can do so using the following syntax ([documented here](https://docs.sylabs.io/guides/3.2/user-guide/cli/singularity_pull.html#singularity-pull)):

`singularity pull docker://quay.io/beckerlab/methylscore:nextflow`
